### ISSUE TITLE
Излишен ред ...

### ISSUE THREAD

**Issue by dabidesh** [BlagovestYurievPetrov/SoftwareUniversity#1]
https://github.com/BlagovestYurievPetrov/SoftwareUniversity/blob/2020a8abaf51bb726408deff430cf8b8330c0f94/JS%20Advanced/Exams/JS%20Advanced%20Exam%2012.02.2021/Parking.js#L54
Без този ред минава, но на мен ми гърми 6-ти тест и сега ще разбера защо. Благодаря!

**Comment by BlagovestYurievPetrov** [comment]
Благодаря за корекцията.
Прочетох условието и забелязах, че този ред се връща само когато метода се
извика с параметър.
Съжалявам за безпокойството!

**Comment by dabidesh** [comment]
Няма нищо, всъщност аз търся помощ!
Лошото, е че не виждам още защо гърми моето ... на толкова елементарна задача!

**Comment by BlagovestYurievPetrov** [comment]
А Вие от Software University Mentors ли сте?
Защото вчера в фб пратих пейстбин на задачата, а сега някак си сте я
намерили в гитхъб и ми е малко странно :D.

**Comment by dabidesh** [comment]
Не, беше сложил препратка към друга задача и тъй намерих github-а ти. Обикновено се мъча до последно, но и обичам да гледам чужди решения – твоето е малко дълго, но ми помогна да видя моята грешка (много е **смешна**:
``` 
Error`The car, you're looking for, is not found.`;
```
).

**Comment by BlagovestYurievPetrov** [comment]
Аха, ок. Радвам се, че съм ти помогнал.
